config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :user_info
  end

  resources :profile do
    resources :skills
  end

  scope 'api' do
    scope 'v1' do
      resources :api_profile
    end
  end

  root 'place#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :skills, dependent: :destroy
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :profile
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :profiles, dependent: :destroy
  has_one :user_info, dependent: :destroy
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  geocoded_by :get_client_ip
  after_validation :geocode

  def get_client_ip
    :client_ip
  end

  belongs_to :user
end

app/controllers/api_profile_controller.rb
class ApiProfileController < ApplicationController
  def index
    profiles = Profile.all
    render json: {status: 'SUCCESS', data: profiles}
  end

  def show
    profile = Profile.includes(:skills).find(params[:id])
    render json: {
        status: 'SUCCESS',
        data: {
            id: profile.id,
            position: profile.position,
            experience: profile.exp_period,
            owner_email: profile.user.email,
            skills: profile.skills
        }
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected
  def after_sign_in_path_for(resource)
    if UserInfo.exists?(current_user.id)
      root_path
    else
      new_user_user_info_path(current_user.id)
    end
  end
end

app/controllers/place_controller.rb
class PlaceController < ApplicationController
  def index
    if current_user
      # Update user IP
      data = UserInfo.find_by_user_id(current_user)
      data.client_ip = request.env['HTTP_X_REAL_IP'] ||= request.env['REMOTE_ADDR']
      data.save
      # Get users in 50km area from you
      near = UserInfo.near("#{current_user.user_info.latitude}, #{current_user.user_info.longitude}", 50)
      @users = User.joins(:user_info).merge(near).includes(:profiles)
    else
      @users = User.includes(:user_info, :profiles)
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = current_user.profiles
  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = Profile.new(get_params)
    @profile.user = current_user
    if @profile.save
      redirect_to profile_skills_path(@profile.id)
    end
  end

  def update
    if @profile.user != current_user
      raise ActionController::RoutingError.new('You must be owner to do this')
    else
      if @profile.update(get_params)
        redirect_to root_path
    end
    end
  end

  def destroy
    if @profile.user == current_user
      @profile.destroy
      redirect_to root_path
    else
      raise ActionController::RoutingError.new('You must be owner to do this')
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def get_params
    params.require(:profile).permit(:position, :exp_period)
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def index
    @skill = Skill.new
    @skills = Skill.where(profile_id: params[:profile_id])
  end

  def create
    @skill = Skill.new(params.require(:skill).permit(:title))
    @skill.profile_id = params[:profile_id]

    if @skill.save
      redirect_to action: 'index'
    end
  end

end

app/controllers/user_info_controller.rb
class UserInfoController < ApplicationController

  def new
    @user_info = UserInfo.new
  end

  def create
    @user_info = UserInfo.new(
        params.require(:user_info).permit(
            :first_name,
            :last_name,
            :age,
            :facebook,
            :twitter,
            :github,
            :country,
            :city
        )
    )
    @user_info.user = current_user
    @user_info.client_ip = request.env['HTTP_X_REAL_IP'] ||= request.env['REMOTE_ADDR']
    if @user_info.save
      redirect_to new_profile_path
    end
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/api_profile_helper.rb
module ApiProfileHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/place_helper.rb
module PlaceHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/rest_helper.rb
module RestHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_info_helper.rb
module UserInfoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceToFace</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!--AIzaSyD15U_Zj5d8J266KweqMO7JDMEv0c98gYA-->
  <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">FaceToFace</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li class="active"><a href="/profile">MultiCV</a></li></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' if current_user%></li>
          <li><%= link_to "Login", new_user_session_path, :method => 'get' if not current_user %></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
    <div class="footer">
      <b>HelloWorldStudio</b> ||
      <%= link_to 'Watch More', 'https://github.com/Killsoft1692' %>
    </div>
  </body>
</html>

app/views/place/index.html.erb
<div class="row">
  <%= image_tag('header.jpg', class:'header_img') %>
  <% dots ='' %>
  <!--Define color of marker-->
  <% dot_color = ['black', 'brown', 'green', 'purple', 'yellow', 'blue', 'gray', 'orange', 'red', 'white'] %>
  <% @users.each do |u| %>
      <!--Define user's markers-->
      <% dots += "markers=color:#{dot_color.sample}%7Clabel:#{u.user_info.first_name.upcase[0]}%7C#{u.user_info.latitude},#{u.user_info.longitude}&" %>
  <% end %>
  <div class="col-md-6">
    <img src="http://maps.googleapis.com/maps/api/staticmap?<%= dots %>size=1024x768&scale=2?key=Your API_KEY" width="100%"/>
  </div>
  <div class="col-md-4">
    <% if current_user %>
      <h4>Near with you:</h4>
        <div class="table-responsive">
          <ul class="list-group">
            <% @users.each do |u| %>
                <li class="list-group-item list-group-item-success"><span class="glyphicon glyphicon-user"></span> <%= u.user_info.first_name %> <%= u.user_info.last_name %> || <%= ((Time.zone.now - u.user_info.age.to_time) /1.year.seconds).floor %> years
                <% if u.user_info.github.present? %>
                  <%= link_to image_tag('github.png',width:20),
                      u.user_info.github, target: '_blank'
                  %>
                <% end %>
                <% if u.user_info.facebook.present? %>
                   <%= link_to image_tag('facebook.png',width:20),
                      u.user_info.facebook, target: '_blank'
                   %>
                <% end %>
                <% if u.user_info.twitter.present? %>
                   <%= link_to image_tag('twitter.png',width:20),
                      u.user_info.twitter, target: '_blank'
                   %>
                <% end %>
                </li>
                <% if u != current_user %>
                    <span class="glyphicon glyphicon-sort"><i> in <%='%.2f' % u.user_info.distance_to([current_user.user_info.latitude, current_user.user_info.longitude], :km) %> km from you</i></span>
                <% end %>
                <table class="table table-striped text-center">
                  <% u.profiles.each do |profile| %>
                      <tr>
                        <td class="text-left"><span class="glyphicon glyphicon-flash"></span><%= link_to profile.position, profile_path(profile) %></td><td class="text-right"><span class="glyphicon glyphicon-time"></span><%= profile.exp_period %></td></tr>
                  <% end %>
                </table>
            <% end %>
      <% else %>
       <h3>Welcome to FaceToFace</h3>
          On the left side you can see our customers.
          <p><b>Tell about your profession.
            You have some cool ideas but you don't know who can help you?
            Create your profiles here and tell people around about you.</b></p>
          <h4>What are you waiting for?!</h4>
      <% end %>
    </ul>
        </div>

  </div>

</div>

app/views/skills/index.html.erb
<div class="col-md-10" style="margin-left: 3%">
  <h3>Manage skills here:</h3>
  <ul class="list-group" style="width: 25%">
    <% @skills.each do |s| %>
      <li class="list-group-item list-group-item-success">
        <%= s.title %>
      </li>
    <% end %>
  </ul>
  <%= form_for @skill, url: {action: :create} do |f| %>
    <p><%= f.text_field :title, placeholder: 'Skill\'s tile', required: true %></p>
    <%= f.submit %>
  <% end %>

</div>

app/views/user_info/new.html.erb
<%= form_for @user_info, url: {action: 'create'} do |f| %>
    <p><%= f.text_field :first_name, placeholder: 'Insert your first name', required: true %></p>
    <p><%= f.text_field :last_name, placeholder: 'Insert your last name', required: true %></p>
    <p><%= f.date_select :age, start_year: 1900 , end_year: 2010, required: true%></p>
    <p><%= f.text_field :facebook, placeholder: 'Facebook'%></p>
    <p><%= f.text_field :twitter, placeholder: 'Twitter'%></p>
    <p><%= f.text_field :github, placeholder: 'GitHub'%></p>
    <p><%= f.text_field :country, placeholder: 'Your country' %></p>
    <p><%= f.text_field :city, placeholder: 'Your city' %></p>
    <%= f.submit %>
<% end %>